---
- name: Add GitLab Runner repository
  copy:
    owner: root
    group: root
    mode: 0644
    dest: /etc/yum.repos.d/gitlab-runner.repo
    content: |+
      [gitlab-runner]
      baseurl = https://packages.gitlab.com/runner/gitlab-runner/el/7/$basearch
      name = GitLab Runner Stable
      gpgcheck = 0
- name: Install gitlab-runner
  package:
    name: gitlab-runner
    state: present
- name: Configure gitlab-runner
  copy:
    owner: root
    group: root
    mode: 0400
    dest: /etc/gitlab-runner/config.toml
    content: |+
      concurrent = 1
      [[runners]]
        name = "shell executor runner"
        executor = "shell"
        shell = "bash"
- name: Start gitlab-runner.service
  systemd:
    name: gitlab-runner.service
    state: started
    enabled: true