---
- name: Verify that gitlab_runner_registration_token is defined if required
  assert:
    that:
      - gitlab_runner_registration_token != None
      - gitlab_runner_registration_token | length > 0
  when: gitlab_runner_register

- name: Install gitlab-runner
  include_tasks: install-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml

- name: Configure gitlab-runner
  import_tasks: configure.yml

- name: Start gitlab-runner.service
  systemd:
    name: gitlab-runner.service
    state: started
    enabled: true
